[explorer]
tile_width = 17
tile_height = 4
double_click_delay = 400

[colors]
background = "#1a1b26"
foreground = "#c0caf5"
error = "#f7768e"
selected_background = "#ffffff66"
selected_foreground = "#c0caf5"
border = "#414868"
border_muted = "#565f89"

[[places]]
path = "/home/edward"
label = "edward"
icon = "🏚️"

[[places]]
path = "/home/edward/Desktop"
label = "Desktop"
icon = "📁"

[[places]]
path = "/home/edward/Downloads"
label = "Downloads"
icon = "📁"

[[places]]
path = "/home/edward/Documents"
label = "Documents"
icon = "📁"

[[places]]
path = "/home/edward/Music"
label = "Music"
icon = "📁"

[[places]]
path = "/home/edward/Videos"
label = "Videos"
icon = "📁"

[[places]]
path = "/home/edward/Pictures"
label = "Pictures"
icon = "📁"

[[bookmarks]]
path = "/home/edward/Projects"
label = "Projects"
icon = "🔖"

[[bookmarks]]
path = "/home/edward/Certificates"
label = "Certificates"
icon = "🔖"

[[drives]]
path = "/"
label = "root"
icon = "💾"
